server:
  port: 8083

spring:
  application:
    name: catalog-service

  datasource:
    url: jdbc:postgresql://orders_db:5432/orders_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  cache:
    type: redis
  data:
    redis:
      host: redis
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: catalog-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
